## Fisher Score- Chisquare  Test For Feature Selection

In [3]:
import pandas as pd
import numpy as np
import seaborn as sns

In [4]:
df = pd.read_csv('train.csv')
df.head()

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S  
3      0            113803  53.1000  C123        S  
4      0            373450   8.0500   NaN        S

In [8]:
df['Family'] = df['SibSp']+df['Parch']

In [11]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 13 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   PassengerId  891 non-null    int64  
 1   Survived     891 non-null    int64  
 2   Pclass       891 non-null    int64  
 3   Name         891 non-null    object 
 4   Sex          891 non-null    object 
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64  
 7   Parch        891 non-null    int64  
 8   Ticket       891 non-null    object 
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object 
 11  Embarked     889 non-null    object 
 12  Family       891 non-null    int64  
dtypes: float64(2), int64(6), object(5)
memory usage: 90.6+ KB


In [34]:
##['sex','embarked','alone','pclass','Survived']
df=df[['Sex','Embarked','Alone','Pclass','Survived']]
df.head()

Sex Embarked  Alone  Pclass  Survived
0    male        S      1       3         0
1  female        C      1       1         1
2  female        S      0       3         1
3  female        S      1       1         1
4    male        S      0       3         0

In [47]:
import numpy as np

### Let's perform label encoding on sex column
ordinal_label = {k: i for i, k in enumerate(df['Sex'].unique(), 0)}
df['Sex'] = df['Sex'].map(ordinal_label)

### let's perform label encoding on embarked
ordinal_label = {k: i for i, k in enumerate(df['Embarked'].unique(), 0)}
df['Embarked'] = df['Embarked'].map(ordinal_label)

/tmp/ipykernel_2452/3209128140.py:5: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Sex'] = df['Sex'].map(ordinal_label)
/tmp/ipykernel_2452/3209128140.py:9: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Embarked'] = df['Embarked'].map(ordinal_label)


In [48]:
df.head()

Sex  Embarked  Alone  Pclass  Survived
0    0         0      1       3         0
1    1         1      1       1         1
2    1         0      0       3         1
3    1         0      1       1         1
4    0         0      0       3         0

In [49]:
### let's perform label encoding on alone
df['Alone']=np.where(df['Alone']==True,1,0)

/tmp/ipykernel_2452/1141751679.py:2: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Alone']=np.where(df['Alone']==True,1,0)


In [50]:
df.head()

Sex  Embarked  Alone  Pclass  Survived
0    0         0      1       3         0
1    1         1      1       1         1
2    1         0      0       3         1
3    1         0      1       1         1
4    0         0      0       3         0

In [51]:
X = df.drop(columns='Survived')
y = df['Survived']

In [52]:
### train Test split is usually done to avaoid overfitting
from sklearn.model_selection import train_test_split

X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.3)

In [53]:
X_train.head()

Sex  Embarked  Alone  Pclass
90     0         0      0       3
615    1         0      1       2
76     0         0      0       3
748    0         0      1       1
595    0         0      1       3

In [54]:
X_train['Sex'].unique()

array([0, 1])

In [55]:
X_train.isnull().sum()

Sex         0
Embarked    0
Alone       0
Pclass      0
dtype: int64

## FS using Chi Square Test

In [56]:
## Perform chi2 test
### chi2 returns 2 values
### Fscore and the pvalue
from sklearn.feature_selection import chi2
f_p_values=chi2(X_train,y_train)

In [57]:
f_p_values

(array([104.62036793,  10.82878401,   8.50688644,  23.98126885]),
 array([1.47928333e-24, 9.99342471e-04, 3.53804926e-03, 9.72774933e-07]))

In [58]:
import pandas as pd
p_values=pd.Series(f_p_values[1])
p_values.index=X_train.columns
p_values

Sex         1.479283e-24
Embarked    9.993425e-04
Alone       3.538049e-03
Pclass      9.727749e-07
dtype: float64

In [59]:
p_values.sort_index(ascending=False)

Sex         1.479283e-24
Pclass      9.727749e-07
Embarked    9.993425e-04
Alone       3.538049e-03
dtype: float64